services:
  postgres:
    image: postgres:16-alpine
    container_name: utn_bd_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: utn_bd
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d utn_bd"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: ./app
    container_name: utn_bd_app
    ports:
      - "5050:5000"
    environment:
      DB_HOST: postgres
      DB_NAME: utn_bd
      DB_USER: admin
      DB_PASS: admin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
