version: '3.8'

services:
  postgres:
    build:
      context: https://github.com/martinmalgor04/utn-sql-playground.git#main
      dockerfile: Dockerfile.postgres
    container_name: utn_bd_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Utn.2026*-
      POSTGRES_DB: utn_bd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d utn_bd"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: https://github.com/martinmalgor04/utn-sql-playground.git#main
      dockerfile: app/Dockerfile
    container_name: utn_bd_app
    environment:
      DB_HOST: postgres
      DB_NAME: utn_bd
      DB_USER: readonly
      DB_PASS: UtnSQL
      DB_ADMIN_USER: admin
      DB_ADMIN_PASS: Utn.2026*-
    ports:
      - "3579:5000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  postgres_data:
